//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public int CleaningID { get; set; }
        public int RoomID { get; set; }
        public int StaffID { get; set; }
        public System.TimeSpan StartHour { get; set; }
        public System.TimeSpan EndHour { get; set; }
        public System.DateTime WorkDay { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
