//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distributions()
        {
            this.Seance = new HashSet<Seance>();
        }
    
        public int DistributionID { get; set; }
        public int MovieID { get; set; }
        public int DistributorID { get; set; }
        public string Dubbing { get; set; }
        public string Subtitle { get; set; }
        public Nullable<bool> is3D { get; set; }
    
        public virtual Distributors Distributors { get; set; }
        public virtual Movies Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seance { get; set; }
    }
}
