//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution_TicketCash
    {
        public int IdSeansu { get; set; }
        public string Tytuł { get; set; }
        public int Sala { get; set; }
        public Nullable<int> CzasTrwania { get; set; }
        public Nullable<System.TimeSpan> GodzSeansu { get; set; }
        public System.DateTime ShowDate { get; set; }
    }
}
