//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myCinemaPlannerDBEntities : DbContext
    {
        public myCinemaPlannerDBEntities()
            : base("name=myCinemaPlannerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cashes> Cashes { get; set; }
        public virtual DbSet<Cleaning> Cleaning { get; set; }
        public virtual DbSet<Distributions> Distributions { get; set; }
        public virtual DbSet<Distributors> Distributors { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Seance> Seance { get; set; }
        public virtual DbSet<Sellings> Sellings { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Technicians> Technicians { get; set; }
        public virtual DbSet<Usage> Usage { get; set; }
    }
}
