//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Realized
    {
        public int OrderID { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
        public Nullable<decimal> PriceInPLN { get; set; }
    }
}
