//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinemaPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usage
    {
        public int CashID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public System.DateTime WorkDay { get; set; }
        public int UsageID { get; set; }
    
        public virtual Cashes Cashes { get; set; }
        public virtual Products Products { get; set; }
    }
}
